name: Build and Publish Docker Images

on:
  push:
    branches:
      #change accordingly to your need
      - release/dev

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-service-log:
    name: Build and Push service-log
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare image name
        id: prep_a
        run: |
          IMAGE_NAME="${{ github.repository }}"
          echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} #GitHub Actions auto gen token

      - name: Extract Docker metadata for service-log
        id: meta_a
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.prep_a.outputs.IMAGE_NAME_LC }}/service-log

      - name: Build and push service-log Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./logservice
          push: true
          tags: ${{ steps.meta_a.outputs.tags }}
          labels: ${{ steps.meta_a.outputs.labels }}